version: "3.9"

services:
  akki-stream-bot:
    container_name: akki-stream-bot
    build: .
    restart: unless-stopped

    environment:
      TZ: Asia/Kolkata

    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro

    command: sh -c "sleep 10 && python3 -m Adarsh"

    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
