name: Auto Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Deploy with password login
      uses: appleboy/ssh-action@master
      with:
        password: ${{ secrets.PASSWORD }}
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USER }}
        # key: ${{ secrets.SSH_KEY }}
        port: 22
        script: |
          cd /srv/my-apps/akki-stream-bot
          eval "$(ssh-agent -s)"
          ssh-add ~/.ssh/id_ed25519_second
          git pull origin main
          docker compose up -d --build akki-stream-bot
          docker system prune -f
          docker ps
          exit
